<div style="display: block;z-index:2;border:1px solid;" class="leightbox1" id="lightbox1">
<div style="padding-top: 30px; padding-bottom: 50px; padding-left:20px;"><strong><?php echo $this->__('Feature currently disabled')?></strong><div class="txt pb30"><?php echo $this->__('Reason:')?><br>
	<?php echo $this->__('License key is invalid or has been expired.')?></div>
	<div style="float:left;" class="txt pb30"><a href="http://www.convertware.com/pricing" title="Pucrhase" target="_blank"><?php echo $this->__('Purchase')?></a><?php echo $this->__(' to unclock all features OR ')?></div><div style="margin-left:50px; float:left;" class="txt pb30"><a href="http://www.convertware.com/softicket" title="Request a license" target="_blank"><?php echo $this->__('Request a license')?></a><?php echo $this->__(' if you already ordered Personalization')?></div><div style="float:right; padding-right:50px;margin-bottom:20px;"><a href="javascript:history.back(1)" style="font:14px Arial,sans-serif; color:black;"><?php echo $this->__('Close and go back')?></a></div>

</div>
</div>
